### ISSUE TITLE
这个项目怎么单独运行 其中的项目啊 

### ISSUE THREAD

**Issue by luhaoaimama1** [Piasy/AndroidPlayground#2]

**Comment by luhaoaimama1** [comment]
每次碰到这种都无奈啊  还有就是  想知道的 你说的官方demo是怎么找到的 求方法~ 真心求

**Comment by Piasy** [comment]
这就是个普通的工程，Android Studio 打开就好了。信息获取，我就是通过搜索引擎，没别的捷径。

**Comment by luhaoaimama1** [comment]
好吧   最后一个问题   看了你的 深入理解 RecyclerView 系列之一：ItemDecoration  感觉真的不错 但是我确实现不了  就是  GridVIew那种 左右无缝隙的   每个item 大小相等 宽高相等的  有没有什么 高招？我实现了 最左边和最右边有缝那种 但是无缝那种却怎么也实现不来。。。

**Comment by Piasy** [comment]
那几个函数我都已经分析得很清楚了，自己动手试试，你可以的

**Comment by luhaoaimama1** [comment]
https://github.com/luhaoaimama1/ZAdapter  的  Dector那个我就尝试了  最后也没找到解决方案。。。无缝  并且 每个item宽高相等 我认为是不可能 。。。recyclerView 貌似做不到~  原谅我的无知
